kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
        from_secret: DOCKER_HUB_USERNAME
    password:
        from_secret: DOCKER_HUB_PASSWORD
    repo: ocamlbench/ocamlspeed
    tags: latest
      when:
        branch:
          - master
